import type { TreeNode } from './types'

export const INIT: TreeNode[] = [
  {
    id: 'work',
    text: 'Work',
    completed: false,
    collapsed: false,
    starred: false,
    children: [
      {
        id: 'work-q2-marketing-launch',
        text: 'Q2 Marketing Launch',
        completed: false,
        collapsed: false,
        starred: false,
        children: [
          {
            id: 'work-q2-draft-email-campaign',
            text: 'Draft email campaign',
            completed: true,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'work-q2-design-landing-page',
            text: 'Design landing page',
            completed: false,
            collapsed: false,
            starred: true,
            children: [],
          },
          {
            id: 'work-q2-set-up-ab-testing',
            text: 'Set up A/B testing',
            completed: false,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'work-q2-schedule-social-posts',
            text: 'Schedule social posts',
            completed: false,
            collapsed: false,
            starred: false,
            children: [],
          },
        ],
      },
      {
        id: 'work-team-sync-prep',
        text: 'Team sync prep',
        completed: false,
        collapsed: false,
        starred: false,
        children: [
          {
            id: 'work-team-sync-compile-weekly-metrics',
            text: 'Compile weekly metrics',
            completed: true,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'work-team-sync-update-roadmap-slides',
            text: 'Update roadmap slides',
            completed: false,
            collapsed: false,
            starred: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 'personal',
    text: 'Personal',
    completed: false,
    collapsed: false,
    starred: false,
    children: [
      {
        id: 'personal-book-dentist-appointment',
        text: 'Book dentist appointment',
        completed: false,
        collapsed: false,
        starred: true,
        children: [],
      },
      {
        id: 'personal-renew-gym-membership',
        text: 'Renew gym membership',
        completed: false,
        collapsed: false,
        starred: false,
        children: [],
      },
      {
        id: 'personal-weekend-trip-planning',
        text: 'Weekend trip planning',
        completed: false,
        collapsed: false,
        starred: false,
        children: [
          {
            id: 'personal-weekend-trip-check-hotel-prices',
            text: 'Check hotel prices',
            completed: true,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'personal-weekend-trip-book-train-tickets',
            text: 'Book train tickets',
            completed: false,
            collapsed: false,
            starred: false,
            children: [],
          },
          {
            id: 'personal-weekend-trip-pack-bag',
            text: 'Pack bag',
            completed: false,
            collapsed: false,
            starred: false,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 'ideas',
    text: 'Ideas',
    completed: false,
    collapsed: false,
    starred: false,
    children: [
      {
        id: 'ideas-build-a-todo-tree-app',
        text: 'Build a To-Do Tree app',
        completed: false,
        collapsed: false,
        starred: true,
        children: [],
      },
      {
        id: 'ideas-write-a-short-story',
        text: 'Write a short story',
        completed: false,
        collapsed: false,
        starred: false,
        children: [],
      },
    ],
  },
]
